package com.itau.api.effective.model;

import com.amazonaws.services.dynamodbv2.datamodeling.*;
import lombok.AllArgsConstructor;
import lombok.Builder;
import lombok.NoArgsConstructor;
import org.springframework.data.annotation.CreatedDate;

@DynamoDBTable(tableName = "EffectiveRenegociation")
@AllArgsConstructor
@NoArgsConstructor
@Builder
public class EffectiveRenegociationModel {

    private String id;
    private String documentId;
    private String transactionId;
    private String originalValue;
    private String discountPercentage;
    private String discountedValue;
    private String effectiveValue;
    private String date;
    private String plots;
    private String installmentValue;
    private String status;
    private String simulationId;
    private String currency;

    @DynamoDBAttribute
    public String getSimulationId() {
        return simulationId;
    }

    public void setSimulationId(String simulationId) {
        this.simulationId = simulationId;
    }

    @DynamoDBHashKey
    @DynamoDBAutoGeneratedKey
    public String getId() {
        return id;
    }

    @DynamoDBAttribute
    public String getDocumentId() {
        return documentId;
    }

    @DynamoDBAttribute
    public String getTransactionId() {
        return transactionId;
    }

    @DynamoDBAttribute
    public String getOriginalValue() {
        return originalValue;
    }

    @DynamoDBAttribute
    public String getDiscountPercentage() {
        return discountPercentage;
    }

    @DynamoDBAttribute
    public String getDiscountedValue() {
        return discountedValue;
    }

    @DynamoDBAttribute
    public String getEffectiveValue() {
        return effectiveValue;
    }

    @DynamoDBAttribute
    public String getStatus() {
        return status;
    }


    @CreatedDate
    @DynamoDBAttribute
    @DynamoDBAutoGeneratedTimestamp(strategy = DynamoDBAutoGenerateStrategy.CREATE)
    public String getDate() {
        return date;
    }

    @DynamoDBAttribute
    public String getPlots() {
        return plots;
    }

    @DynamoDBAttribute
    public String getInstallmentValue() {
        return installmentValue;
    }

    public void setDocumentId(String documentId) {
        this.documentId = documentId;
    }

    public void setTransactionId(String transactionId) {
        this.transactionId = transactionId;
    }

    public void setOriginalValue(String originalValue) {
        this.originalValue = originalValue;
    }

    public void setDiscountPercentage(String discountPercentage) {
        this.discountPercentage = discountPercentage;
    }

    public void setDiscountedValue(String discountedValue) {
        this.discountedValue = discountedValue;
    }

    public void setEffectiveValue(String effectiveValue) {
        this.effectiveValue = effectiveValue;
    }

    public void setDate(String date) {
        this.date = date;
    }

    public void setPlots(String plots) {
        this.plots = plots;
    }

    public void setInstallmentValue(String installmentValue) {
        this.installmentValue = installmentValue;
    }

    public void setId(String id) {
        this.id = id;
    }

    public void setStatus(String status) {
        this.status = status;
    }

    @DynamoDBAttribute
    public String getCurrency() {
        return currency;
    }

    public void setCurrency(String currency) {
        this.currency = currency;
    }

}
